"""create_assignments

Revision ID: 888f30db9cc4
Revises: 942536d565e7
Create Date: 2026-08-04 02:38:47.266239
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '888f30db9cc4'
down_revision: str | Sequence[str] | None = '942536d565e7'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assignments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('subject', sa.String(length=20), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("subject IN ('KOREAN', 'ENGLISH', 'MATH', 'SOCIAL_STUDIES', 'SCIENCE', 'HISTORY', 'ETC')", name='ck_assignments_subject'),
    sa.CheckConstraint('char_length(btrim(title)) BETWEEN 1 AND 100', name='ck_assignments_title_length'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_assignments_user_id_due_at', 'assignments', ['user_id', 'due_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_assignments_user_id_due_at', table_name='assignments')
    op.drop_table('assignments')
    # ### end Alembic commands ###
